/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAL.NhanVienDAL;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Hoang
 */
public class DangNhap extends javax.swing.JFrame {

    /**
     * Creates new form DangNhap
     */
    NhanVienDAL nvDAL = new NhanVienDAL();
    public static String tenDN = null;
    public DangNhap() {
        //setUndecorated(true);
        setSize(580,370);
        initComponents();
        setTitle("Đăng Nhập");
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tftennguoidung = new javax.swing.JTextField();
        btdangnhap = new javax.swing.JButton();
        tfmatkhau = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 102));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tên người dùng");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 150, 46));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 110, 42));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Mật khẩu");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 86, 46));

        tftennguoidung.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tftennguoidung.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tftennguoidung.setText("hoangthai98");
        tftennguoidung.setToolTipText("");
        tftennguoidung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tftennguoidungMouseClicked(evt);
            }
        });
        tftennguoidung.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tftennguoidungKeyPressed(evt);
            }
        });
        getContentPane().add(tftennguoidung, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 150, 30));

        btdangnhap.setBackground(new java.awt.Color(255, 255, 255));
        btdangnhap.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        btdangnhap.setText("Đăng Nhập");
        btdangnhap.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btdangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdangnhapActionPerformed(evt);
            }
        });
        getContentPane().add(btdangnhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 110, 42));

        tfmatkhau.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfmatkhau.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfmatkhau.setText("1998");
        tfmatkhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfmatkhauMouseClicked(evt);
            }
        });
        tfmatkhau.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfmatkhauKeyPressed(evt);
            }
        });
        getContentPane().add(tfmatkhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 150, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon("E:\\HA\\QuanLyNhaHang\\src\\HinhAnh\\button_moi-ban-dang-nhap.png")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 367, -1));

        jLabel5.setBackground(new java.awt.Color(255, 153, 51));
        jLabel5.setForeground(new java.awt.Color(255, 153, 51));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/ezgif.com-resize.gif"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -3, 600, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        tftennguoidung.setText("");
        tfmatkhau.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tftennguoidungMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tftennguoidungMouseClicked
        tftennguoidung.selectAll();
    }//GEN-LAST:event_tftennguoidungMouseClicked

    private void tfmatkhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfmatkhauMouseClicked
        tfmatkhau.selectAll();
    }//GEN-LAST:event_tfmatkhauMouseClicked

    private void tftennguoidungKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tftennguoidungKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            tfmatkhau.requestFocus();
        }
    }//GEN-LAST:event_tftennguoidungKeyPressed

    private void tfmatkhauKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfmatkhauKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            btdangnhap.doClick();
            
        }
        
    }//GEN-LAST:event_tfmatkhauKeyPressed

    private void btdangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdangnhapActionPerformed
        String tengd = tftennguoidung.getText();
        String pass = tfmatkhau.getText();
        if(tftennguoidung.getText().equals("") || tfmatkhau.getText().equals("")) JOptionPane.showMessageDialog(null, "Hãy nhập đầy đủ thông tin đăng nhập!");
        else{
            if(kiemTra(tengd, pass)){
                tenDN = tftennguoidung.getText();
                this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(null, "Sai 'Tên người dùng' hoặc 'Mật khẩu'", "Thông báo", JOptionPane.YES_OPTION);
            }
           
                
        }

    }//GEN-LAST:event_btdangnhapActionPerformed
    public boolean kiemTra(String userName, String pass){
        if(nvDAL.dangNhap(userName, pass)) return true;
        else return false;
    }
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int k = JOptionPane.showConfirmDialog(null, "Thoát và đóng phần mềm?", "Đóng phần mềm", JOptionPane.YES_NO_OPTION);
        if(k == JOptionPane.YES_OPTION){
            this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        }
        else{
            this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btdangnhap;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField tfmatkhau;
    private javax.swing.JTextField tftennguoidung;
    // End of variables declaration//GEN-END:variables
}
