/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import javax.swing.JOptionPane;



/**
 *
 * @author Hoang
 */
public class QuyenAdminGUI extends javax.swing.JFrame {

    /** Creates new form MenuChinh */
    public QuyenAdminGUI() {
        //this.setUndecorated(true);
        initComponents();
        btqlnhanvien.setVisible(false);
        btquanlyban.setVisible(false);
        btquanlytd.setVisible(false);
                
        setSize(1280, 680);
        setLocationRelativeTo(null);
        setVisible(true);
        setResizable(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        bthome = new javax.swing.JButton();
        btorder = new javax.swing.JButton();
        btquanly = new javax.swing.JButton();
        btthongke = new javax.swing.JButton();
        btqlnhanvien = new javax.swing.JButton();
        btquanlyban = new javax.swing.JButton();
        btquanlytd = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(1280, 100));

        bthome.setBackground(new java.awt.Color(51, 255, 204));
        bthome.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        bthome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/yellow-home-icon.png"))); // NOI18N
        bthome.setLabel("HOME");
        bthome.setPreferredSize(new java.awt.Dimension(220, 80));
        bthome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthomeActionPerformed(evt);
            }
        });
        jPanel4.add(bthome);

        btorder.setBackground(new java.awt.Color(51, 255, 0));
        btorder.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btorder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/Finance-Purchase-Order-icon.png"))); // NOI18N
        btorder.setText("ORDER");
        btorder.setPreferredSize(new java.awt.Dimension(220, 80));
        btorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btorderActionPerformed(evt);
            }
        });
        jPanel4.add(btorder);

        btquanly.setBackground(new java.awt.Color(255, 102, 102));
        btquanly.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btquanly.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/drink-coca-cola-icon.png"))); // NOI18N
        btquanly.setText("QUẢN LÝ");
        btquanly.setPreferredSize(new java.awt.Dimension(220, 80));
        btquanly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btquanlyActionPerformed(evt);
            }
        });
        jPanel4.add(btquanly);

        btthongke.setBackground(new java.awt.Color(255, 255, 102));
        btthongke.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btthongke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/script-yellow-icon.png"))); // NOI18N
        btthongke.setText("THỐNG KÊ");
        btthongke.setPreferredSize(new java.awt.Dimension(220, 80));
        btthongke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btthongkeActionPerformed(evt);
            }
        });
        jPanel4.add(btthongke);

        btqlnhanvien.setBackground(new java.awt.Color(153, 255, 153));
        btqlnhanvien.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btqlnhanvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/Office-Customer-Male-Light-icon.png"))); // NOI18N
        btqlnhanvien.setText("NHÂN VIÊN");
        btqlnhanvien.setPreferredSize(new java.awt.Dimension(220, 80));
        btqlnhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btqlnhanvienActionPerformed(evt);
            }
        });
        jPanel4.add(btqlnhanvien);

        btquanlyban.setBackground(new java.awt.Color(204, 204, 255));
        btquanlyban.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btquanlyban.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/Table-SZ-icon (1).png"))); // NOI18N
        btquanlyban.setText("BÀN");
        btquanlyban.setPreferredSize(new java.awt.Dimension(220, 80));
        btquanlyban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btquanlybanActionPerformed(evt);
            }
        });
        jPanel4.add(btquanlyban);

        btquanlytd.setBackground(new java.awt.Color(204, 0, 204));
        btquanlytd.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btquanlytd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/Finance-Purchase-Order-icon (1).png"))); // NOI18N
        btquanlytd.setText("THỰC ĐƠN");
        btquanlytd.setPreferredSize(new java.awt.Dimension(220, 80));
        btquanlytd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btquanlytdActionPerformed(evt);
            }
        });
        jPanel4.add(btquanlytd);

        getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HinhAnh/nh.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5, java.awt.BorderLayout.CENTER);

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));
        jMenuBar1.setForeground(new java.awt.Color(255, 102, 51));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(397, 25));

        jMenu1.setText("   Trang  Chủ   ");
        jMenu1.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        jMenuItem2.setText("Thoát");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        jMenuItem5.setText("Đăng Xuất");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("   Order   ");
        jMenu2.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setText("   Quản  Lý   ");
        jMenu3.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jMenuItem1.setText("Nhân  Viên");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jMenuItem3.setText("Thực  Đơn");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jMenuItem4.setText("Bàn");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("   Thống  Kê   ");
        jMenu4.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        jMenu5.setText("      Trợ Giúp   ");
        jMenu5.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        jMenuItem6.setText("Giới Thiệu");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem6);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        NhanVienGUI nv = new NhanVienGUI();
        nv.setVisible(true);
        //nv.lamMoiNhanVien();
        
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        OrderGUI order = new OrderGUI();
        order.chay();
        
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        ThucDonGUI thucDon = new ThucDonGUI();
        thucDon.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        BanGUI b = new BanGUI();
        b.setVisible(true);
                
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void btquanlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btquanlyActionPerformed
        btorder.setVisible(false);
        btquanly.setVisible(false);
        btthongke.setVisible(false);
        btqlnhanvien.setVisible(true);
        btquanlyban.setVisible(true);
        btquanlytd.setVisible(true);
        
        
    }//GEN-LAST:event_btquanlyActionPerformed

    private void bthomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthomeActionPerformed
        btorder.setVisible(true);
        btquanly.setVisible(true);
        btthongke.setVisible(true);
        btqlnhanvien.setVisible(false);
        btquanlyban.setVisible(false);
        btquanlytd.setVisible(false);
    }//GEN-LAST:event_bthomeActionPerformed

    private void btorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btorderActionPerformed
        OrderGUI order = new OrderGUI();
        order.chay();
    }//GEN-LAST:event_btorderActionPerformed

    private void btthongkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btthongkeActionPerformed
        DoanhThuGUI dt = new DoanhThuGUI();
        dt.setVisible(true);
    }//GEN-LAST:event_btthongkeActionPerformed

    private void btqlnhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btqlnhanvienActionPerformed
        NhanVienGUI nv = new NhanVienGUI();
        nv.setVisible(true);
    }//GEN-LAST:event_btqlnhanvienActionPerformed

    private void btquanlybanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btquanlybanActionPerformed
        BanGUI ban = new BanGUI();
        ban.setVisible(true);
    }//GEN-LAST:event_btquanlybanActionPerformed

    private void btquanlytdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btquanlytdActionPerformed
        ThucDonGUI td = new ThucDonGUI();
        td.setVisible(true);
    }//GEN-LAST:event_btquanlytdActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        
        DoanhThuGUI dt = new DoanhThuGUI();
        dt.setVisible(true);
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        GioiThieu gt =new GioiThieu();
        gt.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        int k = JOptionPane.showConfirmDialog(null, "Đăng xuất?", "Xác nhận!", JOptionPane.YES_NO_OPTION);
        if(k == JOptionPane.YES_NO_OPTION){
            DangNhap dn = new DangNhap();
            dn.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        int k = JOptionPane.showConfirmDialog(null, "Thoát?", "Xác nhận thoát!", JOptionPane.YES_NO_OPTION);
        if(k== JOptionPane.YES_OPTION)  System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int k = JOptionPane.showConfirmDialog(null, "Thoát?", "Xác nhận!", JOptionPane.YES_NO_OPTION);
        if(k == JOptionPane.YES_OPTION){
            this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            DangNhap dn = new DangNhap();
            dn.setVisible(true);
        }
        else{
            this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuyenAdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuyenAdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuyenAdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuyenAdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuyenAdminGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bthome;
    private javax.swing.JButton btorder;
    private javax.swing.JButton btqlnhanvien;
    private javax.swing.JButton btquanly;
    private javax.swing.JButton btquanlyban;
    private javax.swing.JButton btquanlytd;
    private javax.swing.JButton btthongke;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables

}
